// Import necessary dependencies from Redux Toolkit.
import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';

// Define the interface for the state of the SignIn feature.
interface SignInState {
    errStr: string,      // Holds the error string associated with sign-in.
    email: string,       // Stores the user's email for sign-in.
    password: string     // Stores the user's password for sign-in.
}

// Define the initial state for the SignIn feature.
const initialState: SignInState = {
    errStr: "",          // Initialize the error string as empty.
    email: "",           // Initialize the email as empty.
    password: ""         // Initialize the password as empty.
};

// Create a Redux slice for the SignIn feature.
export const signInSlice = createSlice({
    name: 'signIn',                 // Specify the slice name.
    initialState,                  // Provide the initial state.
    reducers: {
        setErrStr: (state: SignInState, action: PayloadAction<string>) => {
            return {
                ...state,            // Preserve the existing state.
                errStr: action.payload   // Update the error string with the provided payload.
            }
        },
        setEmail: (state: SignInState, action: PayloadAction<string>) => {
            return {
                ...state,            // Preserve the existing state.
                email: action.payload   // Update the email with the provided payload.
            }
        },
        setPassword: (state: SignInState, action: PayloadAction<string>) => {
            return {
                ...state,            // Preserve the existing state.
                password: action.payload   // Update the password with the provided payload.
            }
        },
        setInitialState: (state: SignInState) => initialState   // Reset the state to initial state.
    }
});

// Export the action creators generated by the slice.
export const { setErrStr, setEmail, setPassword, setInitialState } = signInSlice.actions;

// Export the reducer function from the slice to be used in Redux store.
export default signInSlice.reducer;
